spring:
  config:
    location: classpath:/application-db.properties,application-dto.yml
  datasource:
    hikari:
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dd-job?allowMultiQueries=true

user:
  password: lalala
zookeeper:
  host: 127.0.0.1:2181

redis:
  host: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


xxl:
  job:
    executor:
      adminAddress: http://localhost:8080/
      appname: fun-coding-xxl-executor
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler/
      logretentiondays: -1
      accessToken:

sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: org.apache.commons.dbcp.BasicDataSource
        url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true
        driver: com.mysql.jdbc.Driver
        username: root
        password: 123456
    config:
      sharding:
        tables:
          user:
            actualDataNodes: ds0.user_$->{0..1}
            tableStrategy:
              inline:
                shardingColumn: id
                algorithmExpression: user_$->(order_id %2)

